site_name: SS Documentation
repo_url: https://github.com/mystara2/notes
site_description: Wiki entries for things
site_author: Mystara

theme:
  name: material

nasv:
  - Home: index.md
  - Windows:
      - Overview: Windows/index.md
  - Minecraft:
      - Overview: Minecraft/index.md


markdown_extensions:
  - attr_list